language: python

python:
- "2.7"
- "3.3"

before_install:
# install dependencies available on pip
- pip install numpy lxml PyYAML --use-mirrors
# install urdf_parser_py
- git clone https://github.com/ros/urdfdom
- cd urdfdom/urdf_parser_py
- python setup.py install
- cd ../../

install:
- python setup.py install

script:
- cd test
- simmechanics_to_urdf
- simmechanics_to_urdf LEGS_MECHANISM.xml legs_simmechanics_options.yaml xml
- simmechanics_to_urdf LEGS_MECHANISM.xml legs_simmechanics_options.yaml graph
