language: python

python:
- "2.7"
- "3.3"
- "3.4"
- "3.5"

before_install:
# install dependencies available on pip
- pip install numpy lxml PyYAML catkin_pkg
# install urdf_parser_py
- git clone https://github.com/ros/urdf_parser_py
- cd urdf_parser_py
- python setup.py install
- cd ../

install:
- python setup.py install

script:
- cd test
- simmechanics_to_urdf LEGS_MECHANISM.xml --yaml legs_simmechanics_options.yaml --csv-joints joint_parameters.csv --output xml
- simmechanics_to_urdf LEGS_MECHANISM.xml --yaml legs_simmechanics_options.yaml --csv-joints joint_parameters.csv --output graph
- simmechanics_to_urdf LEGS_MECHANISM.xml --yaml legs_simmechanics_options.yaml --csv-joints joint_parameters.csv --output xml --outputfile testurdf.urdf
- simmechanics_to_urdf LEGS_MECHANISM.xml --yaml legs_simmechanics_options.yaml --csv-joints joint_parameters.csv --output graph --outputfile testgraph.txt
- simmechanics_to_urdf LEGS_MECHANISM.xml --output graph

after_script:
- rm -f testurdf.urdf
- rm -f testgraph.txt
